### ISSUE TITLE
Error completing 'import os; os.'

### ISSUE THREAD

**Issue by wilywampa** [davidhalter/jedi#936]
This is a report for the error described here: https://github.com/davidhalter/jedi-vim/issues/679#issuecomment-310814395

The following is the result of running `import jedi; jedi.Script('import os; os.').completions()` in Neovim:

```
Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/api/__init__.py", line 179, in completions
    completions = completion.completions()
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/api/completion.py", line 96, in completions
    completion_names = self._get_context_completions()
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/api/completion.py", line 169, in _get_context_completions
    completion_names += self._trailer_completions(dot.get_previous_leaf())
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/api/completion.py", line 210, in _trailer_completions
    completion_names += filter.values()
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/filters.py", line 157, in values
    return self._convert_names(name for name_list in self._used_names.values()
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/filters.py", line 154, in _convert_names
    return [self.name_class(self.context, name) for name in names]
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/filters.py", line 154, in <listcomp>
    return [self.name_class(self.context, name) for name in names]
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/filters.py", line 158, in <genexpr>
    for name in self._filter(name_list))
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/filters.py", line 183, in _filter
    return list(self._check_flows(names))
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/filters.py", line 197, in _check_flows
    self._node_context, self._parser_scope, name, self._origin_scope
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/flow_analysis.py", line 73, in reachability_check
    return _break_check(context, context_scope, first_flow_scope, node)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/flow_analysis.py", line 88, in _break_check
    reachable = _check_if(context, flow_node)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/flow_analysis.py", line 104, in _check_if
    types = context.eval_node(node)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/context.py", line 37, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 215, in eval_element
    definitions = self.goto_definitions(context, if_name)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 462, in goto_definitions
    return helpers.evaluate_call_of_leaf(context, name)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/helpers.py", line 53, in evaluate_call_of_leaf
    return context.eval_node(leaf)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/context.py", line 37, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 247, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 264, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 268, in _eval_element_cached
    return self._eval_element_not_cached(context, element)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 276, in _eval_element_not_cached
    types = self.eval_atom(context, element)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 347, in eval_atom
    search_global=True
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/_compatibility.py", line 213, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/context.py", line 52, in py__getattribute__
    self, name_or_str, name_context, position, search_global, is_goto)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 130, in find_types
    return f.find(filters, attribute_lookup=not search_global)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/finder.py", line 64, in find
    types = self._names_to_types(names, attribute_lookup)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/finder.py", line 147, in _names_to_types
    types = unite(name.infer() for name in names)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/common.py", line 191, in unite
    return set(typ for types in iterable for typ in types)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/common.py", line 191, in <genexpr>
    return set(typ for types in iterable for typ in types)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/finder.py", line 147, in <genexpr>
    types = unite(name.infer() for name in names)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/filters.py", line 79, in infer
    return _name_to_types(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/finder.py", line 193, in _name_to_types
    types = _remove_statements(evaluator, context, node, tree_name)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/finder.py", line 278, in _remove_statements
    types |= context.eval_stmt(stmt, seek_name=name)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/context.py", line 40, in eval_stmt
    return self.evaluator.eval_statement(self, stmt, seek_name)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 135, in eval_statement
    return self._eval_stmt(context, stmt, seek_name)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 151, in _eval_stmt
    types = self.eval_element(context, rhs)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 252, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 264, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 268, in _eval_element_cached
    return self._eval_element_not_cached(context, element)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 289, in _eval_element_not_cached
    types = self.eval_atom(context, first_child)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 347, in eval_atom
    search_global=True
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/_compatibility.py", line 213, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/context.py", line 52, in py__getattribute__
    self, name_or_str, name_context, position, search_global, is_goto)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/__init__.py", line 130, in find_types
    return f.find(filters, attribute_lookup=not search_global)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/finder.py", line 64, in find
    types = self._names_to_types(names, attribute_lookup)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/finder.py", line 147, in _names_to_types
    types = unite(name.infer() for name in names)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/common.py", line 191, in unite
    return set(typ for types in iterable for typ in types)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/common.py", line 191, in <genexpr>
    return set(typ for types in iterable for typ in types)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/finder.py", line 147, in <genexpr>
    types = unite(name.infer() for name in names)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/filters.py", line 79, in infer
    return _name_to_types(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/finder.py", line 197, in _name_to_types
    types = imports.infer_import(context, tree_name)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/imports.py", line 58, in infer_import
    types = importer.follow()
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/imports.py", line 259, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/evaluate/imports.py", line 352, in _do_import
    code = module_file.read()
  File "/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/_compatibility.py", line 31, in read
    return self.loader.get_source(self.string)
AttributeError: module 'sys' has no attribute 'get_source'
```

**Comment by davidhalter** [comment]
Do you also get it when not running in neovim but in a Python REPL?

What's your system like? OS?

**Comment by wilywampa** [comment]
It happens in the regular Python REPL as well. I'm on OS X Sierra with Python 3.6.0.

```
    Python 3.6.0 (default, Dec 24 2016, 08:02:28)
    [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import jedi
    >>> jedi.Script('import os; os.').completions()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/api/__init__.py", line 179, in completions
        completions = completion.completions()
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/api/completion.py", line 96, in completions
        completion_names = self._get_context_completions()
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/api/completion.py", line 169, in _get_context_completions
        completion_names += self._trailer_completions(dot.get_previous_leaf())
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/api/completion.py", line 210, in _trailer_completions
        completion_names += filter.values()
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 157, in values
        return self._convert_names(name for name_list in self._used_names.values()
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 154, in _convert_names
        return [self.name_class(self.context, name) for name in names]
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 154, in <listcomp>
        return [self.name_class(self.context, name) for name in names]
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 158, in <genexpr>
        for name in self._filter(name_list))
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 183, in _filter
        return list(self._check_flows(names))
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 197, in _check_flows
        self._node_context, self._parser_scope, name, self._origin_scope
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/flow_analysis.py", line 73, in reachability_check
        return _break_check(context, context_scope, first_flow_scope, node)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/flow_analysis.py", line 88, in _break_check
        reachable = _check_if(context, flow_node)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/flow_analysis.py", line 104, in _check_if
        types = context.eval_node(node)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/context.py", line 37, in eval_node
        return self.evaluator.eval_element(self, node)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 215, in eval_element
        definitions = self.goto_definitions(context, if_name)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 462, in goto_definitions
        return helpers.evaluate_call_of_leaf(context, name)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/helpers.py", line 53, in evaluate_call_of_leaf
        return context.eval_node(leaf)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/context.py", line 37, in eval_node
        return self.evaluator.eval_element(self, node)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 247, in eval_element
        return self._eval_element_if_evaluated(context, element)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 264, in _eval_element_if_evaluated
        return self._eval_element_cached(context, element)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 268, in _eval_element_cached
        return self._eval_element_not_cached(context, element)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
        return func(*args, **kwargs)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 276, in _eval_element_not_cached
        types = self.eval_atom(context, element)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 347, in eval_atom
        search_global=True
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/_compatibility.py", line 213, in <lambda>
        return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/context.py", line 52, in py__getattribute__
        self, name_or_str, name_context, position, search_global, is_goto)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 130, in find_types
        return f.find(filters, attribute_lookup=not search_global)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
        return func(*args, **kwargs)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 64, in find
        types = self._names_to_types(names, attribute_lookup)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 147, in _names_to_types
        types = unite(name.infer() for name in names)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/common.py", line 191, in unite
        return set(typ for types in iterable for typ in types)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/common.py", line 191, in <genexpr>
        return set(typ for types in iterable for typ in types)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 147, in <genexpr>
        types = unite(name.infer() for name in names)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 79, in infer
        return _name_to_types(self.parent_context.evaluator, self.parent_context, self.tree_name)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 193, in _name_to_types
        types = _remove_statements(evaluator, context, node, tree_name)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 278, in _remove_statements
        types |= context.eval_stmt(stmt, seek_name=name)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/context.py", line 40, in eval_stmt
        return self.evaluator.eval_statement(self, stmt, seek_name)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
        return self._eval_stmt(context, stmt, seek_name)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
        return func(*args, **kwargs)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 151, in _eval_stmt
        types = self.eval_element(context, rhs)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 252, in eval_element
        return self._eval_element_if_evaluated(context, element)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 264, in _eval_element_if_evaluated
        return self._eval_element_cached(context, element)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 268, in _eval_element_cached
        return self._eval_element_not_cached(context, element)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
        return func(*args, **kwargs)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 289, in _eval_element_not_cached
        types = self.eval_atom(context, first_child)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 347, in eval_atom
        search_global=True
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/_compatibility.py", line 213, in <lambda>
        return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/context.py", line 52, in py__getattribute__
        self, name_or_str, name_context, position, search_global, is_goto)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 130, in find_types
        return f.find(filters, attribute_lookup=not search_global)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/debug.py", line 81, in wrapper
        return func(*args, **kwargs)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 64, in find
        types = self._names_to_types(names, attribute_lookup)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 147, in _names_to_types
        types = unite(name.infer() for name in names)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/common.py", line 191, in unite
        return set(typ for types in iterable for typ in types)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/common.py", line 191, in <genexpr>
        return set(typ for types in iterable for typ in types)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 147, in <genexpr>
        types = unite(name.infer() for name in names)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 79, in infer
        return _name_to_types(self.parent_context.evaluator, self.parent_context, self.tree_name)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 197, in _name_to_types
        types = imports.infer_import(context, tree_name)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/imports.py", line 58, in infer_import
        types = importer.follow()
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/imports.py", line 259, in follow
        return self._do_import(self.import_path, self.sys_path_with_modifications())
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/evaluate/imports.py", line 352, in _do_import
        code = module_file.read()
      File "/Users/jniehus/Documents/dev/py3.6env/lib/python3.6/site-packages/jedi/_compatibility.py", line 31, in read
        return self.loader.get_source(self.string)
    AttributeError: module 'sys' has no attribute 'get_source'
```

**Comment by davidhalter** [comment]
That is very strange. It's clearly a bug. I'd like other people to try this as well, because I cannot reproduce it.

Do you have it across python versions?

**Comment by wilywampa** [comment]
It works fine in 3.6.1. I have a feeling it's just something wrong with my environment.

**Comment by davidhalter** [comment]
My guess is that your environment is indeed somehow broken. I'm not sure what it is, it could for example be Python files/libraries on your path (typically your working directory) or something else that leads to these very strange issues.

I'll close for now, because I really don't think that it's a Jedi issue. Happy to reopen if you investigate more and think that it's really a Jedi issue. Basically you would need to identify where that `sys` is coming from.

**Comment by eloaf** [comment]
Same problem here. I installed jedi and instantly got this issue on OSX Sierra python 3.5.

**Comment by davidhalter** [comment]
Please try to debug it. Try to find where sys is coming from. It doesn't make any sense.
