### ISSUE TITLE
Error with cv2 on OS X

### ISSUE THREAD

**Issue by mikew** [davidhalter/jedi#777]
Both Python and OpenCV were installed with Homebrew:

``` sh
brew install python
brew install homebrew/science/opencv3 --HEAD --with-contrib
```

Using Jedi from master I am not able to get any completions:

``` python
>>> import cv2
>>> cv2.__version__
'3.1.0-dev'
>>> import jedi
>>> code = 'import cv2; cv2.'
>>> jedi.Script(code, 1, len(code), None).completions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jedi/api/__init__.py", line 169, in completions
    completions = completion.completions()
  File "jedi/api/completion.py", line 90, in completions
    completion_names = self._get_context_completions()
  File "jedi/api/completion.py", line 164, in _get_context_completions
    completion_names += self._trailer_completions(atom_expr)
  File "jedi/api/completion.py", line 210, in _trailer_completions
    names, self._module.get_statement_for_position(self._position)
  File "jedi/evaluate/finder.py", line 78, in filter_definition_names
    if filter_private_variable(scope, origin):
  File "jedi/evaluate/finder.py", line 621, in filter_private_variable
    instance = scope.get_parent_scope()
AttributeError: 'NoneType' object has no attribute 'get_parent_scope'
```

**Comment by davidhalter** [comment]
Can you retry with the current Jedi master?

**Comment by mikew** [comment]
It doesn't work with Jedi master, but does with `v0.9.0`.

**Comment by stardiviner** [comment]
I have same issue . link here.
https://github.com/jorgenschaefer/elpy/issues/1003

**Comment by TheMikeyR** [comment]
I have the same issue [here](https://github.com/DamnWidget/anaconda/issues/578#issuecomment-258122313)

**Comment by TheMikeyR** [comment]
@davidhalter @mikew 
Currently I'm having version `0.9.0` I guess it's bundled with anaconda? but I still have the issue

**Comment by davidhalter** [comment]
Well thanks for the update. Ironically the latest branch will completely stop using this way of scopes.

Therefore this bug might not be relevant anymore. But since only about 30% of the tests are passing in that branch I'm not even asking you to check it out. :)

I will let you know when Jedi is good enough!

**Comment by TheMikeyR** [comment]
@davidhalter thanks a lot! Can't wait :)

**Comment by stardiviner** [comment]
Does current jedi master branch fixed this bug now?

**Comment by davidhalter** [comment]
Maybe. I haven't tested. So if anyone can retest.

**Comment by stardiviner** [comment]
After my test, still not fixed.

**Comment by stardiviner** [comment]
Any update on this?

**Comment by davidhalter** [comment]
Still an issue with `0.11.0`?

**Comment by stardiviner** [comment]
Yes, still issue in latest elpy and jedi 0.11.0.

**Comment by davidhalter** [comment]
I have just tried it with

```
>>> cv2.__version__
'2.4.9.1'
>>> jedi.__version__
'0.11.1'
```

I cannot reproduce it. Can anyone of you that still experiences this issue please give me an up-to-date traceback? The code that is mentioned above doesn't exist anymore.

**Comment by stardiviner** [comment]
```python
    import cv2
    import jedi
    
    code = 'import cv2; cv2.'
    print(jedi.Script(code, 1, len(code), None).completions())
```
Get result:
```
[<Completion: cv2>, <Completion: os>, <Completion: sys>, <Completion: __doc__>, <Completion: __file__>, <Completion: __name__>, <Completion: __package__>]
```

Might related to cv2 package init file:
`~/.virtualenvs/python3.6/lib/python3.6/site-packages/cv2/__init__.py`
```python
import sys
import os

# FFMPEG dll is not found on Windows without this
os.environ["PATH"] += os.pathsep + os.path.dirname(os.path.realpath(__file__))

from . import cv2
sys.modules['cv2'] = cv2
```

**Comment by TheMikeyR** [comment]
@davidhalter I don't have any issues regarding autocompletition in ipython and sublime text 3 (using anaconda package).
```cv2: 3.2.0
jedi: 0.10.2```

When running the script above it prints a long list like this, I've only included a snippet:
```
 <Completion: distanceTransform>,
 <Completion: distanceTransformWithLabels>,
 <Completion: divide>,
 <Completion: DMatch>,
 <Completion: dnn>,
 <Completion: DRAW_MATCHES_FLAGS_DEFAULT>,
 <Completion: DRAW_MATCHES_FLAGS_DRAW_OVER_OUTIMG>,
 <Completion: DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS>,
 <Completion: DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS>,
 <Completion: drawChessboardCorners>,
 <Completion: drawContours>,
 <Completion: drawKeypoints>,
 <Completion: drawMarker>,
 <Completion: drawMatches>,
 <Completion: DrawMatchesFlags_DEFAULT>,
 <Completion: DrawMatchesFlags_DRAW_OVER_OUTIMG>,
 <Completion: DrawMatchesFlags_DRAW_RICH_KEYPOINTS>,
 <Completion: DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS>,
 <Completion: drawMatchesKnn>,
 <Completion: DualTVL1OpticalFlow_create>,
 <Completion: edgePreservingFilter>,
 <Completion: eigen>,
 <Completion: ellipse>,
 <Completion: ellipse2Poly>,
 <Completion: equalizeHist>,
 <Completion: erode>,
 <Completion: Error>,
 <Completion: error>,
 <Completion: estimateAffine2D>,
 <Completion: estimateAffine3D>,
```
