### ISSUE TITLE
Method imported seen as a module type instead of a function

### ISSUE THREAD

**Issue by jmagnette** [davidhalter/jedi#1208]
Hi,
I'm writting to you because I cannot find a way to solve my autocompletion tool since I upgraded jedi from version 0.9.0 to 0.12.1 (with parso 0.3.1).

The use case is the following:
I have a file "trial.py" with inside:
`
my_variable = 42

def my_method(arg1="test"):
    pass
`

Then I'm writing another python code (in another file or console) that does:
`
from trial import my_variable, my_method

my_
`
And I'm trying to get the autocompletion on the "my_" part.
Jedi does find, using the Script.completions(), the two names "my_variable" and "my_method" but the completion.type of "my_method" is not a function but a module type.

With version 0.9.0 it was working well. With version 0.12.1, must I do something more to access "my_method" signature or to at least know it is a function and not just a variable ? Or is it a bug/intended feature change of Jedi ?

Best regards,
Jérémie

**Comment by micbou** [comment]
Does completing `from trial import ` return `my_variable` and `my_method`? If it doesn't, this means that Jedi can't find them (it probably doesn't find the `trial` module) and assumes they are modules. Is the `trial.py` file in the same directory as the other file or in the Python path? If not, that's probably the issue.

**Comment by jmagnette** [comment]
Completing `from trial import` does show the `my_variable` and `my_method`, but as module type, not function type for my_method. So it does find the `trial `module.
The file is in a folder referenced by the python path, the other example is done in a "custom" console with jedi support, so it should have access to it.

As said, this was working perfectly with 0.9.0. I still see `my_variable` and `my_method` when doing autocompletion, but `my_method` doesn't have the same type anymore, and it seems Jedi is not able to access the signature of it.

If I add a 
```
def my_function():
     pass
```
in the small code before trying to autocomplete on `my_`, then I also see `my_function` with the function type (as expected)

**Comment by micbou** [comment]
That's strange. I can't reproduce. Which version of Python?

**Comment by jmagnette** [comment]
Python 3.5.5, with anaconda 3.5.2

**Comment by jmagnette** [comment]
Strange, I can't reproduce this issue anymore...
I guess I had made a mistake in handling Jedi output when trying to distinguish properties from methods.
Sorry for that. (I'm closing this issue)
