### ISSUE TITLE
jedi does not work with python 3.9 embedded

### ISSUE THREAD

**Issue by rarafy** [davidhalter/jedi#1810]
I ran the following code in interactive mode.
```
>>> import jedi
>>> source = '''
... import json
... json.lo'''
>>> script = jedi.Script(source, path='example.py')
```
As a result, I received this error
```
Traceback (most recent call last):
  File "E:\UnityProjectStudioRis\Published Projects\2021\PythonDotNet_WebGL\Assets\StreamingAssets\embedded-python\lib\site-packages\jedi\evaluate\compiled\subprocess\__init__.py", line 242, in _send
    is_exception, traceback, result = pickle_load(self._process.stdout)
  File "E:\UnityProjectStudioRis\Published Projects\2021\PythonDotNet_WebGL\Assets\StreamingAssets\embedded-python\lib\site-packages\jedi\_compatibility.py", line 464, in pickle_load
    return pickle.load(file, encoding='bytes')
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\UnityProjectStudioRis\Published Projects\2021\PythonDotNet_WebGL\Assets\StreamingAssets\embedded-python\lib\site-packages\jedi\api\environment.py", line 74, in _get_subprocess
    info = self._subprocess._send(None, _get_info)
  File "E:\UnityProjectStudioRis\Published Projects\2021\PythonDotNet_WebGL\Assets\StreamingAssets\embedded-python\lib\site-packages\jedi\evaluate\compiled\subprocess\__init__.py", line 250, in _send
    raise InternalError(
jedi.api.exceptions.InternalError: The subprocess E:\UnityProjectStudioRis\Published Projects\2021\PythonDotNet_WebGL\Assets\StreamingAssets\embedded-python\python.exe has crashed (EOFError('Ran out of input'), stderr=<empty/not available (ValueError('read of closed file'))>).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\UnityProjectStudioRis\Published Projects\2021\PythonDotNet_WebGL\Assets\StreamingAssets\embedded-python\lib\site-packages\jedi\api\__init__.py", line 107, in __init__
    self._evaluator = Evaluator(
  File "E:\UnityProjectStudioRis\Published Projects\2021\PythonDotNet_WebGL\Assets\StreamingAssets\embedded-python\lib\site-packages\jedi\evaluate\__init__.py", line 94, in __init__
    self.compiled_subprocess = environment.get_evaluator_subprocess(self)
  File "E:\UnityProjectStudioRis\Published Projects\2021\PythonDotNet_WebGL\Assets\StreamingAssets\embedded-python\lib\site-packages\jedi\api\environment.py", line 113, in get_evaluator_subprocess
    return EvaluatorSubprocess(evaluator, self._get_subprocess())
  File "E:\UnityProjectStudioRis\Published Projects\2021\PythonDotNet_WebGL\Assets\StreamingAssets\embedded-python\lib\site-packages\jedi\api\environment.py", line 76, in _get_subprocess
    raise InvalidPythonEnvironment(
jedi.api.environment.InvalidPythonEnvironment: Could not get version information for 'E:\\UnityProjectStudioRis\\Published Projects\\2021\\PythonDotNet_WebGL\\Assets\\StreamingAssets\\embedded-python\\python.exe': InternalError("The subprocess E:\\UnityProjectStudioRis\\Published Projects\\2021\\PythonDotNet_WebGL\\Assets\\StreamingAssets\\embedded-python\\python.exe has crashed (EOFError('Ran out of input'), stderr=<empty/not available (ValueError('read of closed file'))>).")
```
It seems that jedi does not work with Python 3.9 embedded.

**Comment by rarafy** [comment]
@davidhalter Thank you for reply.
I tried:
```
import jedi
sc=''' '''
script = jedi.Script(sc, path='example.py', environment=jedi.InterpreterEnvironment())
```
Then I got an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'jedi' has no attribute 'InterpreterEnvironment'
```
