### ISSUE TITLE
'CompiledObject' object has no attribute 'params'

### ISSUE THREAD

**Issue by ColinDuquesnoy** [davidhalter/jedi#373]
Hi, 

I have an issue when I try to print the parameters of a call def. 

This used to work with Jedi 0.7.0. The error happens with both python 2.7 and python 3.3.

For example, running this script :

``` python
import jedi
print(jedi.__version__)
code = "open("
s = jedi.Script(code)
defs = s.call_signatures()
for call_def in defs:
    for p in call_def.params:
        print(p)
```

leads to the following traceback:

```
0.8.0-alpha1
Traceback (most recent call last):
  File "D:/test.py", line 7, in <module>
    for p in call_def.params:
  File "C:\Python27\lib\site-packages\jedi-0.8.0_alpha1-py2.7.egg\jedi\api\classes.py", line 599, in params
    return sub.params[1:]  # ignore self
AttributeError: 'CompiledObject' object has no attribute 'params'
```
