### ISSUE TITLE
Getting docstring of namespace completion raises AttributeError

### ISSUE THREAD

**Issue by HedgehogCode** [davidhalter/jedi#1890]
If I try to run `docstring()` on a completion for a namespace I get an `AttributeError`.

Try the following script to reproduce the issue:
```python
import os
import shutil
import jedi

# Prepare a module in a namespace
os.makedirs("mynamespace", exist_ok=True)
with open("mynamespace/mymodule.py", "w") as f:
    f.write("print('Hello world')")

# Prepare file to autocomplete
with open("script.py", "w") as f:
    f.write("import mynamespa") # Trying to complete "import mynamespace"

# Run autocompletion
completions = jedi.Script(path="script.py").complete()  # completions = [<Completion: mynamespace>]
docstring = completions[0].docstring()  # <<< FAILS
print(docstring)

# Cleanup
shutil.rmtree("mynamespace")
os.remove("script.py")
```
Traceback:
```
Traceback (most recent call last):
  File "/home/benjamin/misc/jedi/bug_namespace_docs.py", line 16, in <module>
    docstring = completions[0].docstring()  # <<< FAILS
  File "/home/benjamin/misc/jedi/jedi/api/classes.py", line 685, in docstring
    return super().docstring(raw=raw, fast=fast)
  File "/home/benjamin/misc/jedi/jedi/api/classes.py", line 305, in docstring
    signature_text = self._get_docstring_signature()
  File "/home/benjamin/misc/jedi/jedi/api/classes.py", line 703, in _get_docstring_signature
    return super()._get_docstring_signature()
  File "/home/benjamin/misc/jedi/jedi/api/classes.py", line 317, in _get_docstring_signature
    for signature in self._get_signatures(for_docstring=True)
  File "/home/benjamin/misc/jedi/jedi/api/classes.py", line 570, in _get_signatures
    names = convert_names([self._name], prefer_stubs=True)
  File "/home/benjamin/misc/jedi/jedi/inference/gradual/conversion.py", line 152, in convert_names
    return _python_to_stub_names(names, fallback_to_python=prefer_stubs)
  File "/home/benjamin/misc/jedi/jedi/inference/utils.py", line 16, in wrapper
    return list(func(*args, **kwargs))
  File "/home/benjamin/misc/jedi/jedi/inference/gradual/conversion.py", line 126, in _python_to_stub_names
    for x in _python_to_stub_names([n], fallback_to_python=fallback_to_python):
  File "/home/benjamin/misc/jedi/jedi/inference/utils.py", line 16, in wrapper
    return list(func(*args, **kwargs))
  File "/home/benjamin/misc/jedi/jedi/inference/gradual/conversion.py", line 132, in _python_to_stub_names
    v = name.get_defining_qualified_value()
  File "/home/benjamin/misc/jedi/jedi/inference/names.py", line 251, in get_defining_qualified_value
    if context.is_module() or context.is_class():
AttributeError: 'NoneType' object has no attribute 'is_module'
```

Using `git bisect` I found that the bug first appeared in commit https://github.com/davidhalter/jedi/commit/2ec3d72151d1072fa22861aef07ba6fc170e3781.

**Comment by davidhalter** [comment]
Thanks a lot for the detailed reproduction.
