### ISSUE TITLE
Error when trying to complete attributes for an instance of a class with decorated __init__

### ISSUE THREAD

**Issue by eugenhu** [davidhalter/jedi#1606]
When I run
```python
import jedi

code = """from typing import TypeVar

T = TypeVar('T')

def my_decorator(x: T) -> T:
    return x

class MyClass:
    @my_decorator
    def __init__(self) -> None:
        self.my_attribute = 123

def my_function(x: MyClass) -> int:
    return x."""

script = jedi.Script(code)
completions = script.complete(14, 13)

print(completions)
```
I get
```
AttributeError: 'Class' object has no attribute 'get_params'
```

Running the same code again but with the line with `@my_decorator` commented out works fine and the program prints
```
[<Completion: my_attribute>, <Completion: __annotations__>, <Completion: __class__>, <Completion: __delattr__>, <Completion: __dict__>, <Completion: __dir__>, <Completion: __doc__>, <Completion: __eq__>, <Completion: __format__>, <Completion: __getattribute__>, <Completion: __hash__>, <Completion: __init__>, <Completion: __init_subclass__>, <Completion: __module__>, <Completion: __ne__>, <Completion: __new__>, <Completion: __reduce__>, <Completion: __reduce_ex__>, <Completion: __repr__>, <Completion: __setattr__>, <Completion: __sizeof__>, <Completion: __slots__>, <Completion: __str__>]
```

I am using Python 3.8.2 and Jedi 0.17.0.

**Comment by davidhalter** [comment]
Can you try master? It works for me there, however it doesn't work on 0.17.0

**Comment by eugenhu** [comment]
It works on master for me as well, thanks.
